version: '3'
services:

  db:
    container_name: db
    #작성
    volumes:
      - dbdata:/var/lib/mysql

  web:
    container_name: web
    #작성
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  app:
  dbdata:
