version: '3'
services:

  web:
    container_name: web
    #작성
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh

  nginx:
    container_name: nginx
    #작성
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    depends_on:
      - web

volumes:
  static:
  media: