# Generated by Django 3.2.16 on 2023-07-15 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='accounts.user'),
            preserve_default=False,
        ),
    ]
