# Generated by Django 3.2.16 on 2023-07-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='feeling',
            field=models.CharField(choices=[('-1', 'Negative'), ('0', 'Neutral'), ('1', 'Positive')], default='-1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='intensity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='main_emotion',
            field=models.CharField(choices=[('sad', 'Sad'), ('scared', 'Scared'), ('joyful', 'Joyful'), ('powerful', 'Powerful'), ('peaceful', 'Peaceful'), ('mad', 'Mad')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='sub_emotion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
